export const projectTagHash = {
  'fintech': 'Fintech',
  'consumer': 'Consumer',
  'ai_ml': 'AI/ML',
  'social': 'Social',
  'crypto_blockchain': 'Crypto/Blockchain',
  'creator_tools': 'Creator Tools' ,
  'community': 'Community',
  'e_commerce': 'E-commerce',
  'b2b_sass': 'B2B Sass',
  'no_code': 'No Code',
  'biotech': 'Biotech',
  'climate': 'Climate',
  'future_of_work': 'Future of Work',
  'hardware': 'Hardware',
  'marketplace': 'Marketplace',
  'dev_tools': 'Dev Tools',
  'productivity': 'Productivity',
  'music': 'Music'
}