export const LogEvents = {
  'CREATE_USERNAME': 'create_username',
  'PICK_USER_INTERESTS': 'pick_user_interests',
  'FOLLOW_RECOMMENDED_USERS': 'follow_recommended_users',
  'CREATE_PROJECT_FIRST_TIME': 'create_project_first_time',
  'SET_PROJECT_CATEGORY_FIRST_TIME': 'set_project_category_first_time',
  'SET_PROJECT_TAGS_FIRST_TIME': 'set_project_tags_first_time',
  'CREATE_PROJECT': 'create_project',
  'SET_PROJECT_CATEGORY': 'set_project_category',
  'SET_PROJECT_TAGS': 'set_project_tags',
  'SKIP_PROJECT_CREATE': 'skip_project_create',
  'FINISH_FOLLOWING_RECOMMENDED_USERS': 'finish_following_recommended_users',
  'CREATE_GOAL': 'create_goal',
  'CREATE_TASK': 'create_task',
  'COMPLETE_GOAL': 'complete_goal',
  'COMPLETE_ONBOARDING_GOAL': 'complete_onboarding_goal',
  'COMPLETE_TASK': 'complete_task',
  'COMPLETE_ONBOARDING_TASK': 'complete_onboarding_task',
  'ADD_COMPLETE_GOAL_MESSAGE': 'add_complete_goal_message',
  'ADD_COMPLETE_TASK_MESSAGE': 'add_complete_task_message',
  'INVITE_INTERNAL_COLLABORATOR': 'invite_internal_collaborator',
  'INVITE_EXTERNAL_COLLABORATOR': 'invite_external_collaborator'
}