const countries = [
  { value: "Afghanistan", code: "AF" },
  { value: "Albania", code: "AL" },
  { value: "Algeria", code: "DZ" },
  { value: "Andorra", code: "AD" },
  { value: "Angola", code: "AO" },
  { value: "Antigua and Barbuda", code: "AG" },
  { value: "Argentina", code: "AR" },
  { value: "Armenia", code: "AM" },
  { value: "Australia", code: "AU" },
  { value: "Austria", code: "AT" },
  { value: "Azerbaijan", code: "AZ" },
  { value: "Bahamas", code: "BS" },
  { value: "Bahrain", code: "BH" },
  { value: "Bangladesh", code: "BD" },
  { value: "Barbados", code: "BB" },
  { value: "Belarus", code: "BY" },
  { value: "Belgium", code: "BE" },
  { value: "Belize", code: "BZ" },
  { value: "Benin", code: "BJ" },
  { value: "Bhutan", code: "BT" },
  { value: "Bolivia", code: "BO" },
  { value: "Bosnia and Herzegovina", code: "BA" },
  { value: "Botswana", code: "BW" },
  { value: "Brazil", code: "BR" },
  { value: "Brunei", code: "BN" },
  { value: "Bulgaria", code: "BG" },
  { value: "Burkina Faso", code: "BF" },
  { value: "Burundi", code: "BI" },
  { value: "Côte d'Ivoire", code: "CI" },
  { value: "Cabo Verde", code: "CV" },
  { value: "Cambodia", code: "KH" },
  { value: "Cameroon", code: "CM" },
  { value: "Canada", code: "CA" },
  { value: "Central African Republic", code: "CF" },
  { value: "Chad", code: "TD" },
  { value: "Chile", code: "CL" },
  { value: "China", code: "CN" },
  { value: "Colombia", code: "CO" },
  { value: "Comoros", code: "KM" },
  { value: "Congo (Congo-Brazzaville)", code: "CG" },
  { value: "Costa Rica", code: "CR" },
  { value: "Croatia", code: "HR" },
  { value: "Cuba", code: "CU" },
  { value: "Cyprus", code: "CY" },
  { value: "Czechia (Czech Republic)", code: "CZ" },
  { value: "Democratic Republic of the Congo", code: "CD" },
  { value: "Denmark", code: "DK" },
  { value: "Djibouti", code: "DJ" },
  { value: "Dominica", code: "DM" },
  { value: "Dominican Republic", code: "DO" },
  { value: "Ecuador", code: "EC" },
  { value: "Egypt", code: "EG" },
  { value: "El Salvador", code: "SV" },
  { value: "Equatorial Guinea", code: "GQ" },
  { value: "Eritrea", code: "ER" },
  { value: "Estonia", code: "EE" },
  { value: "Eswatini (fmr. Swaziland)", code: "SZ" },
  { value: "Ethiopia", code: "ET" },
  { value: "Fiji", code: "FJ" },
  { value: "Finland", code: "FI" },
  { value: "France", code: "FR" },
  { value: "Gabon", code: "GA" },
  { value: "Gambia", code: "GM" },
  { value: "Georgia", code: "GE" },
  { value: "Germany", code: "DE" },
  { value: "Ghana", code: "GH" },
  { value: "Greece", code: "GR" },
  { value: "Grenada", code: "GD" },
  { value: "Guatemala", code: "GT" },
  { value: "Guinea", code: "GN" },
  { value: "Guinea-Bissau", code: "GW" },
  { value: "Guyana", code: "GY" },
  { value: "Haiti", code: "HT" },
  { value: "Holy See", code: "VA" },
  { value: "Honduras", code: "HN" },
  { value: "Hungary", code: "HU" },
  { value: "Iceland", code: "IS" },
  { value: "India", code: "IN" },
  { value: "Indonesia", code: "ID" },
  { value: "Iran", code: "IR" },
  { value: "Iraq", code: "IQ" },
  { value: "Ireland", code: "IE" },
  { value: "Israel", code: "IL" },
  { value: "Italy", code: "IT" },
  { value: "Jamaica", code: "JM" },
  { value: "Japan", code: "JP" },
  { value: "Jordan", code: "JO" },
  { value: "Kazakhstan", code: "KZ" },
  { value: "Kenya", code: "KE" },
  { value: "Kiribati", code: "KI" },
  { value: "Kuwait", code: "KW" },
  { value: "Kyrgyzstan", code: "KG" },
  { value: "Laos", code: "LA" },
  { value: "Latvia", code: "LV" },
  { value: "Lebanon", code: "LB" },
  { value: "Lesotho", code: "LS" },
  { value: "Liberia", code: "LR" },
  { value: "Libya", code: "LY" },
  { value: "Liechtenstein", code: "LI" },
  { value: "Lithuania", code: "LT" },
  { value: "Luxembourg", code: "LU" },
  { value: "Madagascar", code: "MG" },
  { value: "Malawi", code: "MW" },
  { value: "Malaysia", code: "MY" },
  { value: "Maldives", code: "MV" },
  { value: "Mali", code: "ML" },
  { value: "Malta", code: "MT" },
  { value: "Marshall Islands", code: "MH" },
  { value: "Mauritania", code: "MR" },
  { value: "Mauritius", code: "MU" },
  { value: "Mexico", code: "MX" },
  { value: "Micronesia", code: "FM" },
  { value: "Moldova", code: "MD" },
  { value: "Monaco", code: "MC" },
  { value: "Mongolia", code: "MN" },
  { value: "Montenegro", code: "ME" },
  { value: "Morocco", code: "MA" },
  { value: "Mozambique", code: "MZ" },
  { value: "Myanmar (formerly Burma)", code: "MM" },
  { value: "Namibia", code: "NA" },
  { value: "Nauru", code: "NR" },
  { value: "Nepal", code: "NP" },
  { value: "Netherlands", code: "NL" },
  { value: "New Zealand", code: "NZ" },
  { value: "Nicaragua", code: "NI" },
  { value: "Niger", code: "NE" },
  { value: "Nigeria", code: "NG" },
  { value: "North Korea", code: "KP" },
  { value: "North Macedonia (formerly Macedonia)", code: "MK" },
  { value: "Norway", code: "NO" },
  { value: "Oman", code: "OM" },
  { value: "Pakistan", code: "PK" },
  { value: "Palau", code: "PW" },
  { value: "Palestine State", code: "PS" },
  { value: "Panama", code: "PA" },
  { value: "Papua New Guinea", code: "PG" },
  { value: "Paraguay", code: "PY" },
  { value: "Peru", code: "PE" },
  { value: "Philippines", code: "PH" },
  { value: "Poland", code: "PL" },
  { value: "Portugal", code: "PT" },
  { value: "Qatar", code: "QA" },
  { value: "Romania", code: "RO" },
  { value: "Russia", code: "RU" },
  { value: "Rwanda", code: "RW" },
  { value: "Saint Kitts and Nevis", code: "KN" },
  { value: "Saint Lucia", code: "LC" },
  { value: "Saint Vincent and the Grenadines", code: "VC" },
  { value: "Samoa", code: "WS" },
  { value: "San Marino", code: "SM" },
  { value: "Sao Tome and Principe", code: "ST" },
  { value: "Saudi Arabia", code: "SA" },
  { value: "Senegal", code: "SN" },
  { value: "Serbia", code: "RS" },
  { value: "Seychelles", code: "SC" },
  { value: "Sierra Leone", code: "SL" },
  { value: "Singapore", code: "SG" },
  { value: "Slovakia", code: "SK" },
  { value: "Slovenia", code: "SI" },
  { value: "Solomon Islands", code: "SB" },
  { value: "Somalia", code: "SO" },
  { value: "South Africa", code: "ZA" },
  { value: "South Korea", code: "KR" },
  { value: "South Sudan", code: "SS" },
  { value: "Spain", code: "ES" },
  { value: "Sri Lanka", code: "LK" },
  { value: "Sudan", code: "SD" },
  { value: "Surivalue", code: "SR" },
  { value: "Sweden", code: "SE" },
  { value: "Switzerland", code: "CH" },
  { value: "Syria", code: "SY" },
  { value: "Tajikistan", code: "TJ" },
  { value: "Tanzania", code: "TZ" },
  { value: "Thailand", code: "TH" },
  { value: "Timor-Leste", code: "TL" },
  { value: "Togo", code: "TG" },
  { value: "Tonga", code: "TO" },
  { value: "Trinidad and Tobago", code: "TT" },
  { value: "Tunisia", code: "TN" },
  { value: "Turkey", code: "TR" },
  { value: "Turkmenistan", code: "TM" },
  { value: "Tuvalu", code: "TV" },
  { value: "Uganda", code: "UG" },
  { value: "Ukraine", code: "UA" },
  { value: "United Arab Emirates", code: "AE" },
  { value: "United Kingdom", code: "GB" },
  { value: "United States of America", code: "US" },
  { value: "Uruguay", code: "UY" },
  { value: "Uzbekistan", code: "UZ" },
  { value: "Vanuatu", code: "VU" },
  { value: "Venezuela", code: "VE" },
  { value: "Vietnam", code: "VN" },
  { value: "Yemen", code: "YE" },
  { value: "Zambia", code: "ZM" },
  { value: "Zimbabwe", code: "ZW" },
];

export default countries;
