on:
  pull_request:
    paths:
      - 'wondrous-web/**/**.ts'
      - 'wondrous-web/**/**.js'
    types:
      - opened
      - synchronize

name: Web - Lint and Test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
      - run: yarn
      - run: yarn lint


